language: node_js
node_js:
  - 8
cache: yarn

script:
  - yarn lint
  - yarn coverage
  - yarn publish-coverage
  - yarn compile

deploy:
  provider: npm
  email: paolo.scanferla@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
  skip_cleanup: true
